# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    ports: 
         - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
     MYSQL_DATABASE: dbname
     MYSQL_PASSWORD: test
     MYSQL_ROOT_PASSWORD: test
    volumnes:
      - ./db_data:/var/lib/mysql

  www:
    build: .
    ports: 
        - 80:80
    volumes:
        - /Users/carlosvasquez/Desktop/personal/historiaclinica:/var/www/html
    links:
        - db
    networks:
        - default 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test 
    ports:
      - 8080:80